version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "2.2.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

nuget:
  account_feed: true
  project_feed: true

platform: Any CPU
configuration: Release

before_build:
- cmd: nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

artifacts:
- path: '\devRant.NET\bin\Debug\devRant.NET.dll'
  name: Binaries
- path: '**\*.nupkg'
  name: NuGet

deploy:

  # Deploy to GitHub Releases
- provider: GitHub
  auth_token:
    secure: LlOS2bO3/Vhd/g/HhFB1cI3CrvTPX7LqJ4ZrnNxQ2mWWAV1ajxgNRWURW5qgeHOe
  artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                # release from master branch only

# Deploying to NuGet feed
- provider: NuGet
  api_key:
    secure: DfeuttFMmrX863fmm6HL5Yd/JcJMYwNjTzxXWuLi8t4AkRYZxM1fAnaVM3Non7HC
  skip_symbols: false
  artifact: /.*\.nupkg/